#!/bin/sh
# prints currently selected text to stdout
xclip -o -selection clipboard | xargs -0 node ~/projects/grown-up-english-vocabulary-learning/build/src/cli-view/index.js translate --text | xargs -0 notify-send
